version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "todolist"
    ports:
      - "3306:3306"
    networks:
      - mysql-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - mysql-network

networks: 
  mysql-network:
    driver: bridge