version: '3.1'

services:

  go:
    build:
      context: .
      dockerfile: Dockerfile-local
    volumes:
      - .:/app
    ports:
      - 3000:3000
      - 3001:3001
    environment:
      - DATA_BASE_URL=root:admin@tcp(db:3306)/todolist
      - DRIVER_NAME=mysql
      - PORT=3000
      - JWT_SECRET_KEY=0f99e5ac-76bd-11ee-b962-0242ac120002-0f99e5ac-76bd-11ee-b962-0242ac120002-0f99e5ac-76bd-11ee-b962-0242ac120002
    depends_on:
      - db
    networks:
      - mysql-network

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "todolist"
    ports:
      - "3306:3306"
    networks:
      - mysql-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - mysql-network

networks: 
  mysql-network:
    driver: bridge